name: analysis_logger
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  firebase_analytics: ^10.0.3
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
