name: ranking_note_app
description: Flutter App Template is a project that introduces an approach to architecture and project structure for developing Flutter apps.
publish_to: "none"
version: 1.0.0+10

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cloud_firestore: ^4.1.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  firebase_analytics: ^10.0.6
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_dynamic_links: ^5.0.6
  firebase_messaging: ^14.1.2
  firebase_performance: ^0.9.0+6
  firebase_remote_config: ^3.0.6
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.1
  gap: ^2.0.0
  google_sign_in: ^5.1.0
  hooks_riverpod: ^2.1.1
  image_picker: ^0.8.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  linked_scroll_controller: ^0.2.0
  material_design_icons_flutter: ^6.0.7096
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^3.0.2
  routemaster: ^1.0.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.8
  sign_in_with_apple: ^4.0.0
  sort_key_generator: ^0.2.0+1
  textfield_tags: ^2.0.0+1
  tuple: ^2.0.0
  uuid: ^3.0.4
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.0.0
  build_runner: ^2.1.4
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  json_serializable: ^6.0.1

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
  assets:
    style: dot-delimiter

flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
